server:
  port: 8003

spring:
  application:
    name: stock

  config:
    import: "classpath:/env.yml"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/${mysql.db_name}
    username: ${mysql.username}
    password: ${mysql.password}

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

